# Generated by Django 5.0 on 2025-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/user/profiles/default', upload_to='media/user/profiles'),
        ),
    ]
