# Generated by Django 5.0 on 2025-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/blog/categories/default.webp', upload_to='media/blog/categories/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='media/blog/thumbnails/default', upload_to='media/blog/thumbnails/'),
        ),
    ]
